
LunarLanderContinuous-v2:
  n_timesteps: !!float 5e5
  policy:  'SACMlpAggregatePolicy'
  batch_size: 256
  learning_starts: 1000
  policy_kwargs: {'source_policy_paths': ['logs/sac_scratch/LunarLanderContinuous-v2_13-40_1/LunarLanderContinuous-v2.pkl',
                                          'logs/sac_scratch/LunarLanderContinuous-v2_13-30_1/LunarLanderContinuous-v2.pkl',
                                          'logs/sac_scratch/LunarLanderContinuous-v2_33-40_1/LunarLanderContinuous-v2.pkl',
                                          'logs/sac_scratch/LunarLanderContinuous-v2_33-30_1/LunarLanderContinuous-v2.pkl'],
                  'SDW': True,
                  'no_bias': True}

