---
LunarLanderContinuous-v2:
  batch_size: 256
  learning_starts: 1000
  n_timesteps: 500000.0
  policy: SACTwoLayerMlpAggregatePolicy
  policy_kwargs:
    SDW: false
    no_bias: false
    source_policy_paths:
    - logs/sac_scratch/LunarLanderContinuous-v2_MainEnginePower1626-SideEnginePower074-Scale4132-InitialRandom75329-SideEngineHeight1466-SideEngineAway1044_1/LunarLanderContinuous-v2.pkl
    - logs/sac_scratch/LunarLanderContinuous-v2_MainEnginePower2853-SideEnginePower051-Scale3368-InitialRandom64814-SideEngineHeight1981-SideEngineAway1278_1/LunarLanderContinuous-v2.pkl
    - logs/sac_scratch/LunarLanderContinuous-v2_MainEnginePower327-SideEnginePower145-Scale310-InitialRandom66053-SideEngineHeight1796-SideEngineAway1759_1/LunarLanderContinuous-v2.pkl
    - logs/sac_scratch/LunarLanderContinuous-v2_MainEnginePower2066-SideEnginePower103-Scale254-InitialRandom68523-SideEngineHeight1401-SideEngineAway1729_1/LunarLanderContinuous-v2.pkl
